# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: FetchRSSandDeploy

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: 	macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
    - run: node -v
    - run: brew install mint
    - run: mint run --silent MarcoEidinger/OsmiumAtlas@main > blogs.json
    - run: cp blogs.json src/
    - run: npm install
    - run: npm run build
    - name: Push to gh-pages
      run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git clone "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" out
          cd out
          git checkout gh-pages
          git rm -rf .
          cd ..
          cp -a build/. out/.
          cd out
          git add -A
          git commit -m "Automated deployment to GitHub Pages: ${GITHUB_SHA}" --allow-empty
          git push origin gh-pages
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
