# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: FetchRSSandDeploy

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: node -v
    - run: brew install mint
    - run: mint run MarcoEidinger/iDDBlockChecker
    - run: idd-blog-checker --save-as-file --yello
    - name: Push to gh-pages
      run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git clone "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" out
          cd out
          git checkout gh-pages-alt
          git rm -rf .
          cd ..
          cp -a docs/. out/.
          cd out
          git add -A
          git commit -m "Automated deployment to GitHub Pages: ${GITHUB_SHA}" --allow-empty
          git push origin gh-pages-alt
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
